# Generated by Django 5.0 on 2023-12-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_savedproduct'),
        ('catalog', '0007_rating'),
    ]

    operations = [
    ]
