# Generated by Django 5.0 on 2023-12-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
        ('catalog', '0006_savedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saved_products',
            field=models.ManyToManyField(blank=True, related_name='saved_products', to='catalog.savedproduct'),
        ),
    ]
